# Generated by Django 3.2.15 on 2024-03-14 19:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_kk', models.CharField(max_length=255, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_kk', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Порядок оформления заказа',
                'verbose_name_plural': 'Порядок оформления заказа',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfoProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_kk', models.CharField(max_length=255, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_kk', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Защита персональных данных пользователей',
                'verbose_name_plural': 'Защита персональных данных пользователей',
            },
        ),
        migrations.CreateModel(
            name='PublicOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_kk', models.CharField(max_length=255, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_kk', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Публичная оферта',
                'verbose_name_plural': 'Публичная оферта',
            },
        ),
        migrations.CreateModel(
            name='PublicOfferForIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Публичная оферта для физических лиц',
                'verbose_name_plural': 'Публичная оферта для физических лиц',
            },
        ),
        migrations.CreateModel(
            name='Refunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_kk', models.CharField(max_length=255, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_kk', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Правила возврата денежных средств',
                'verbose_name_plural': 'Правила возврата денежных средств',
            },
        ),
        migrations.CreateModel(
            name='SiteRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_kk', models.CharField(max_length=255, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_kk', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Правила пользования сайтом',
                'verbose_name_plural': 'Правила пользования сайтом',
            },
        ),
    ]
