# Generated by Django 3.2.15 on 2023-04-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='content_kz',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='abouttheproject',
            old_name='content_kz',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='abouttheproject',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='content_kz',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='orderrules',
            old_name='content_kz',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='orderrules',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='personalinfoprotection',
            old_name='content_kz',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='personalinfoprotection',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='publicoffer',
            old_name='content_kz',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='publicoffer',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='refunds',
            old_name='content_kz',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='refunds',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='siterules',
            old_name='content_kz',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='siterules',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='content_kz',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='title_kz',
            new_name='title_kk',
        ),
    ]
