# Generated by Django 3.2.15 on 2024-03-14 19:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import medtour.guides.instances
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметьте, если удалён тур', verbose_name='Удалён?')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100, verbose_name='Название гида')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Общая информация')),
                ('currency', models.IntegerField(blank=True, choices=[(0, 'USD'), (1, 'KZT'), (2, 'UZS'), (3, 'KGS'), (4, 'EUR')], default=1, null=True, verbose_name='Валюта')),
                ('BIN', models.CharField(blank=True, max_length=16, null=True)),
                ('IIK', models.CharField(blank=True, max_length=50, null=True)),
                ('BIK', models.CharField(blank=True, max_length=15, null=True)),
                ('requisites', models.CharField(blank=True, max_length=50, null=True, verbose_name='Для предоплаты (IBAN)')),
                ('email', models.EmailField(blank=True, help_text='Пожалуйста напишите ваш эмейл', max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес организации')),
                ('working_time', models.TextField(blank=True, null=True, verbose_name='Время работы')),
                ('youtube_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на Youtube')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота адреса')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта адреса')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Слаг')),
                ('is_top', models.BooleanField(default=False, verbose_name='Хиты продаж?')),
                ('is_moderated', models.BooleanField(db_index=True, default=False, verbose_name='Прошел модерацию')),
                ('is_subscribed', models.BooleanField(db_index=True, default=False, help_text='Отметьте, если он подписан', verbose_name='Подписан?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Гид',
                'verbose_name_plural': 'Гиды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Слаг')),
                ('photo', models.ImageField(default='/static/images/default.svg', upload_to='banners')),
                ('icon', models.ImageField(default='/static/images/cart.svg', upload_to='category_icons')),
                ('icon_active', models.ImageField(default='/static/images/cart.svg', upload_to='category_icons')),
                ('title_color', models.CharField(default='#FFFFFF', max_length=10)),
                ('column', models.CharField(default='two', max_length=10)),
            ],
            options={
                'verbose_name': 'Категория гида',
                'verbose_name_plural': 'Категории гидов',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='GuideProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметьте, если удалён тур', verbose_name='Удалён?')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название программы')),
                ('photo', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=medtour.guides.instances.get_program_path, verbose_name='Изображение программы')),
                ('description', models.TextField(verbose_name='Описание программы')),
                ('program', models.TextField(verbose_name='Программа')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('venue_lon', models.FloatField(verbose_name='Долгота места встречи')),
                ('venue_lat', models.FloatField(verbose_name='Широта места встречи')),
                ('venue_address', models.CharField(max_length=200, verbose_name='Адрес места встречи')),
                ('hide', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('complexity', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=10, verbose_name='Сложность')),
                ('duration', models.SmallIntegerField(default=0)),
                ('duration_type', models.CharField(choices=[('minutes', 'Минут'), ('hours', 'Час'), ('days', 'День'), ('weeks', 'Неделя')], default='minutes', max_length=10, verbose_name='Тип времени продолжительности')),
                ('seats_count', models.IntegerField(default=0, verbose_name='Количество мест')),
                ('remarks', models.CharField(blank=True, default='Примечание', max_length=50, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Программа гида',
                'verbose_name_plural': 'Программы гидов',
            },
        ),
        migrations.CreateModel(
            name='GuideShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя изображения')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to=medtour.guides.instances.get_shots_path, verbose_name='Изображение')),
                ('guide', models.ForeignKey(help_text='Прикрепленный гид', on_delete=django.db.models.deletion.CASCADE, related_name='guide_shots', to='guides.guide', verbose_name='Гид')),
            ],
            options={
                'verbose_name': 'Изображение гида',
                'verbose_name_plural': 'Изображения гидов',
            },
        ),
        migrations.CreateModel(
            name='GuideServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_services', to='guides.guide', verbose_name='Гид')),
            ],
            options={
                'verbose_name': 'Услуга гида',
                'verbose_name_plural': 'Услуги гида',
            },
        ),
        migrations.CreateModel(
            name='GuideReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Сервис')),
                ('location', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Местоположение')),
                ('staff', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Персонал')),
                ('proportion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Соотношение цена/качество')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(20, message='Минимальная длина отзыва должна превышать 20 символа')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_reviews', to='guides.guide')),
            ],
            options={
                'verbose_name': 'Отзыв тура',
                'verbose_name_plural': 'Отзывы тура',
                'ordering': ('-created_at',),
            },
        ),
    ]
