# Generated by Django 3.2.15 on 2023-03-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_auto_20230324_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='working_time',
            field=models.TextField(blank=True, null=True, verbose_name='Время работы'),
        ),
    ]
