# Generated by Django 3.2.15 on 2023-03-28 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar'),
        ('guides', '0005_remove_guide_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='org',
            field=models.OneToOneField(help_text='Прикрепленная организация к гиду', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='users.organization', verbose_name='Организация'),
        ),
    ]
