# Generated by Django 3.2.15 on 2023-03-30 09:15

from django.db import migrations, models
import medtour.guides.instances
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0008_alter_guideprogram_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guideprogram',
            old_name='program_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='guideprogram',
            name='program',
            field=models.TextField(default=1, verbose_name='Программа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guideprogram',
            name='description',
            field=models.TextField(verbose_name='Описание программы'),
        ),
        migrations.AlterField(
            model_name='guideprogram',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to=medtour.guides.instances.get_program_path, verbose_name='Изображение программы'),
            preserve_default=False,
        ),
    ]
