# Generated by Django 3.2.15 on 2023-03-31 07:32

from django.db import migrations, models
import medtour.guides.instances
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0009_auto_20230330_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprogram',
            name='seats_count',
            field=models.IntegerField(default=0, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='guideprogram',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=medtour.guides.instances.get_program_path, verbose_name='Изображение программы'),
        ),
    ]
