# Generated by Django 3.2.15 on 2023-05-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0010_auto_20230331_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprogram',
            name='duration',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guideprogram',
            name='duration_type',
            field=models.CharField(choices=[('minutes', 'Минут'), ('hours', 'Час'), ('days', 'День'), ('weeks', 'Неделя')], default='minutes', max_length=10, verbose_name='Тип времени продолжительности'),
        ),
    ]
