# Generated by Django 3.2.15 on 2023-06-02 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_city'),
        ('guides', '0011_auto_20230517_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_cities', to='users.city', verbose_name='Город'),
        ),
    ]
