# Generated by Django 3.2.15 on 2023-06-06 05:39

from django.db import migrations, models

from medtour.utils import unique_slug_generator


def slug_generate_objects(apps, schema_editor):
    GuideModel = apps.get_model('guides', 'Guide')
    for guide in GuideModel.objects.all():
        # Update objects
        slug = unique_slug_generator(guide, guide.title)
        guide.slug = slug
        guide.save()


def reverse_objects(apps, schema_editor):
    # Object removal code
    ...


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0012_guide_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Слаг'),
        ),
        migrations.RunPython(slug_generate_objects, reverse_objects),
    ]
