# Generated by Django 3.2.15 on 2023-06-07 15:06

from django.db import migrations, models
import django.db.models.deletion


def create_objects(apps, schema_editor):
    CategoryModel = apps.get_model('guides', 'GuideCategory')
    if not CategoryModel.objects.filter(pk=1).exists():
        CategoryModel.objects.create(
            pk=1,
            title='Активный отдых',
            slug='aktivnyi-otdykh'
        )


def reverse_create_objects(apps, schema_editor):
    # Object removal code
    ...


class Migration(migrations.Migration):
    dependencies = [
        ('guides', '0013_guide_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория гида',
                'verbose_name_plural': 'Категории гидов',
                'ordering': ('title',),
            },
        ),
        migrations.RunPython(create_objects, reverse_create_objects),
        migrations.AddField(
            model_name='guide',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='guides',
                                    to='guides.guidecategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]



