# Generated by Django 3.2.15 on 2023-06-13 06:40

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0016_auto_20230608_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprogram',
            name='children_age',
            field=models.SmallIntegerField(default=3, verbose_name='Возраст детей'),
        ),
        migrations.AddField(
            model_name='guideprogram',
            name='completion_site',
            field=models.CharField(default='г. Алматы, ул. Назарбаева 1а', max_length=100, verbose_name='Место встречи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guideprogram',
            name='distance',
            field=models.SmallIntegerField(default=1, verbose_name='Дистанция'),
        ),
        migrations.AddField(
            model_name='guideprogram',
            name='distance_unit',
            field=models.CharField(choices=[('m', 'метр'), ('km', 'км')], default='km', max_length=2, verbose_name='Единица измерения дистанции'),
        ),
        migrations.AddField(
            model_name='guideprogram',
            name='excluded_services',
            field=models.ManyToManyField(blank=True, related_name='program_excluded_services', to='guides.GuideServices', verbose_name='Не включенные услуги'),
        ),
        migrations.AddField(
            model_name='guideprogram',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('kz', 'Казахский'), ('uz', 'Узбекский'), ('tj', 'Таджикский'), ('kg', 'Кыргызский'), ('cn', 'Китайский'), ('fr', 'Французский'), ('es', 'Испанский'), ('it', 'Итальянский')], default=['en', 'kz', 'ru'], max_length=29),
        ),
        migrations.AlterField(
            model_name='guideprogram',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='program_services', to='guides.GuideServices', verbose_name='Включенные услуги'),
        ),
    ]
