# Generated by Django 3.2.15 on 2023-06-13 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0017_auto_20230613_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='guides.guideprogram')),
            ],
            options={
                'verbose_name': 'Расписание программы',
                'verbose_name_plural': 'Расписание программ',
            },
        ),
        migrations.CreateModel(
            name='ProgramPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terrain', models.CharField(max_length=200, verbose_name='Местность')),
                ('description', models.TextField(verbose_name='Описание местности')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='guides.guideprogram')),
            ],
            options={
                'verbose_name': 'Местность программы',
                'verbose_name_plural': 'Местности программ',
            },
        ),
    ]
