# Generated by Django 4.1.9 on 2023-06-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guides", "0019_auto_20230613_1325"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guidecategory",
            name="icon_active",
        ),
        migrations.AddField(
            model_name="guidecategory",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
