# Generated by Django 4.1.9 on 2023-06-14 08:16

from django.db import migrations, models
import django.db.models.deletion
import medtour.guides.instances
import sorl.thumbnail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("guides", "0021_alter_guidecategory_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guideprogram",
            name="photo",
        ),
        migrations.AddField(
            model_name="guideprogram",
            name="backpack_weight",
            field=models.CharField(
                choices=[
                    ("light", "Лёгкий (базовые вещи и перекус)"),
                    ("medium", "Средний (портфель до 20 кг)"),
                    ("heavy", "Тяжёлый (багаж до 50 кг)"),
                ],
                default="light",
                max_length=10,
                verbose_name="Вес рюкзака",
            ),
        ),
        migrations.AddField(
            model_name="guideprogram",
            name="type",
            field=models.CharField(
                choices=[("individual", "Индивидуальный"), ("group", "Групповой")],
                default="group",
                max_length=10,
                verbose_name="Тип программы",
            ),
        ),
        migrations.CreateModel(
            name="ProgramShots",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(db_index=True, editable=False, verbose_name="order")),
                ("name", models.CharField(blank=True, max_length=50, null=True, verbose_name="Имя изображения")),
                (
                    "photo",
                    sorl.thumbnail.fields.ImageField(
                        upload_to=medtour.guides.instances.get_program_path, verbose_name="Изображение"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="Укажите программу, к которой хотите прикрепить фото",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_shots",
                        to="guides.guideprogram",
                        verbose_name="Программа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение программы",
                "verbose_name_plural": "Изображения прогамм",
            },
        ),
    ]
