# Generated by Django 4.1.9 on 2023-06-19 10:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("guides", "0022_remove_guideprogram_photo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guidereview",
            options={"ordering": ("-created_at",), "verbose_name": "Отзыв гида", "verbose_name_plural": "Отзывы гида"},
        ),
        migrations.AlterField(
            model_name="guideprogram",
            name="backpack_weight",
            field=models.CharField(
                choices=[
                    ("light", "Лёгкий (базовые вещи и перекус)"),
                    ("medium", "Средний (портфель до 20 кг)"),
                    ("heavy", "Тяжёлый (багаж до 50 кг)"),
                ],
                max_length=10,
                verbose_name="Вес рюкзака",
            ),
        ),
        migrations.AlterField(
            model_name="guideprogram",
            name="children_age",
            field=models.SmallIntegerField(verbose_name="Возраст детей"),
        ),
        migrations.AlterField(
            model_name="guideprogram",
            name="complexity",
            field=models.CharField(
                choices=[("easy", "Лёгкий"), ("medium", "Средний"), ("hard", "Сложный")],
                max_length=10,
                verbose_name="Сложность",
            ),
        ),
        migrations.AlterField(
            model_name="guideprogram",
            name="distance",
            field=models.SmallIntegerField(verbose_name="Дистанция"),
        ),
        migrations.AlterField(
            model_name="guideprogram",
            name="distance_unit",
            field=models.CharField(
                choices=[("m", "метр"), ("km", "км")], max_length=2, verbose_name="Единица измерения дистанции"
            ),
        ),
        migrations.AlterField(
            model_name="guideprogram",
            name="duration",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="guideprogram",
            name="duration_type",
            field=models.CharField(
                choices=[("minutes", "Минут"), ("hours", "Час"), ("days", "День"), ("weeks", "Неделя")],
                max_length=10,
                verbose_name="Тип времени продолжительности",
            ),
        ),
        migrations.AlterField(
            model_name="guideprogram",
            name="languages",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("ru", "Русский"),
                    ("en", "Английский"),
                    ("kz", "Казахский"),
                    ("uz", "Узбекский"),
                    ("tj", "Таджикский"),
                    ("kg", "Кыргызский"),
                    ("cn", "Китайский"),
                    ("fr", "Французский"),
                    ("es", "Испанский"),
                    ("it", "Итальянский"),
                ],
                max_length=29,
            ),
        ),
        migrations.AlterField(
            model_name="guideprogram",
            name="seats_count",
            field=models.IntegerField(verbose_name="Количество мест"),
        ),
        migrations.AlterField(
            model_name="guideprogram",
            name="type",
            field=models.CharField(
                choices=[("individual", "Индивидуальный"), ("group", "Групповой")],
                max_length=10,
                verbose_name="Тип программы",
            ),
        ),
        migrations.CreateModel(
            name="ProgramReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "service",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Сервис",
                    ),
                ),
                (
                    "location",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Местоположение",
                    ),
                ),
                (
                    "staff",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Персонал",
                    ),
                ),
                (
                    "proportion",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Соотношение цена/качество",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                20, message="Минимальная длина отзыва должна превышать 20 символа"
                            )
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_reviews",
                        to="guides.guideprogram",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв программы",
                "verbose_name_plural": "Отзывы программы",
                "ordering": ("-created_at",),
            },
        ),
    ]
