# Generated by Django 4.1.9 on 2023-06-30 03:23

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


def delete_objects(apps, schema_editor):
    ProgramShots = apps.get_model('guides', 'ProgramShots')
    ProgramShots.objects.all().delete()


def reverse_pass(apps, schema_editor):
    # Object removal code
    ...


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0022_alter_tourbookingweekdays_days"),
        ("guides", "0023_alter_guidereview_options_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_objects, reverse_pass),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(db_index=True, editable=False, verbose_name="order")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="Отметьте, если удалён тур", verbose_name="Удалён?"),
                ),
                ("deleted_at", models.DateTimeField(blank=True, editable=False, null=True)),
                ("name", models.CharField(max_length=255, verbose_name="Название программы")),
                (
                    "type",
                    models.CharField(
                        choices=[("individual", "Индивидуальный"), ("group", "Групповой")],
                        max_length=10,
                        verbose_name="Тип программы",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Цена", null=True)),
                ("venue_lon", models.FloatField(verbose_name="Долгота места встречи")),
                ("venue_lat", models.FloatField(verbose_name="Широта места встречи")),
                ("venue_address", models.CharField(max_length=200, verbose_name="Адрес места встречи")),
                ("hide", models.BooleanField(default=False, verbose_name="Скрыть")),
                (
                    "complexity",
                    models.CharField(
                        choices=[("easy", "Лёгкий"), ("medium", "Средний"), ("hard", "Сложный")],
                        max_length=10,
                        verbose_name="Сложность",
                    ),
                ),
                ("duration", models.SmallIntegerField()),
                (
                    "duration_type",
                    models.CharField(
                        choices=[("minutes", "Минут"), ("hours", "Час"), ("days", "День"), ("weeks", "Неделя")],
                        max_length=10,
                        verbose_name="Тип времени продолжительности",
                    ),
                ),
                (
                    "backpack_weight",
                    models.CharField(
                        choices=[
                            ("light", "Лёгкий (базовые вещи и перекус)"),
                            ("medium", "Средний (портфель до 20 кг)"),
                            ("heavy", "Тяжёлый (багаж до 50 кг)"),
                        ],
                        max_length=10,
                        verbose_name="Вес рюкзака",
                    ),
                ),
                ("seats_count", models.IntegerField(verbose_name="Количество мест")),
                (
                    "remarks",
                    models.CharField(
                        blank=True, default="Примечание", max_length=50, null=True, verbose_name="Примечание"
                    ),
                ),
                ("children_age", models.SmallIntegerField(verbose_name="Возраст детей")),
                ("distance", models.SmallIntegerField(verbose_name="Дистанция")),
                (
                    "distance_unit",
                    models.CharField(
                        choices=[("m", "метр"), ("km", "км")], max_length=2, verbose_name="Единица измерения дистанции"
                    ),
                ),
                (
                    "languages",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("ru", "Русский"),
                            ("en", "Английский"),
                            ("kz", "Казахский"),
                            ("uz", "Узбекский"),
                            ("tj", "Таджикский"),
                            ("kg", "Кыргызский"),
                            ("cn", "Китайский"),
                            ("fr", "Французский"),
                            ("es", "Испанский"),
                            ("it", "Итальянский"),
                        ],
                        max_length=29,
                    ),
                ),
                ("completion_site", models.CharField(max_length=100, verbose_name="Место встречи")),
            ],
            options={
                "verbose_name": "Программа гида",
                "verbose_name_plural": "Программы гидов",
            },
        ),
        migrations.CreateModel(
            name="ProgramServices",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, verbose_name="Название услуги")),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guide_services",
                        to="tours.tour",
                        verbose_name="Контрагент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуги программы",
                "verbose_name_plural": "Услуги программы",
            },
        ),
        migrations.RemoveField(
            model_name="guideprogram",
            name="excluded_services",
        ),
        migrations.RemoveField(
            model_name="guideprogram",
            name="guide",
        ),
        migrations.RemoveField(
            model_name="guideprogram",
            name="services",
        ),
        migrations.RemoveField(
            model_name="guidereview",
            name="guide",
        ),
        migrations.RemoveField(
            model_name="guidereview",
            name="user",
        ),
        migrations.RemoveField(
            model_name="guideservices",
            name="guide",
        ),
        migrations.RemoveField(
            model_name="guideshots",
            name="guide",
        ),
        migrations.RenameModel(
            old_name="ProgramSchedule",
            new_name="ProgramInfoSchedule",
        ),
        migrations.DeleteModel(
            name="Guide",
        ),
        migrations.DeleteModel(
            name="GuideReview",
        ),
        migrations.DeleteModel(
            name="GuideServices",
        ),
        migrations.DeleteModel(
            name="GuideShots",
        ),
        migrations.AddField(
            model_name="program",
            name="excluded_services",
            field=models.ManyToManyField(
                blank=True,
                related_name="program_excluded_services",
                to="guides.programservices",
                verbose_name="Не включенные услуги",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="program_services",
                to="guides.programservices",
                verbose_name="Включенные услуги",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="programs", to="tours.tour"
            ),
        ),
        migrations.AlterField(
            model_name="programinfoschedule",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="schedules", to="guides.program"
            ),
        ),
        migrations.AlterField(
            model_name="programplaces",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="places", to="guides.program"
            ),
        ),
        migrations.AlterField(
            model_name="programreview",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="program_reviews", to="guides.program"
            ),
        ),
        migrations.AlterField(
            model_name="programshots",
            name="program",
            field=models.ForeignKey(
                help_text="Укажите программу, к которой хотите прикрепить фото",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_shots",
                to="guides.program",
                verbose_name="Программа",
            ),
        ),
        migrations.DeleteModel(
            name="GuideProgram",
        ),
    ]
