# Generated by Django 3.2.15 on 2023-02-10 09:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметьте, если удалён тур', verbose_name='Удалён?')),
                ('title', models.CharField(default='1 местн. номера', max_length=50)),
                ('place_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('hide', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('remarks', models.CharField(blank=True, default='Примечание', max_length=50, null=True, verbose_name='Примечание')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='tours.tour')),
            ],
            options={
                'verbose_name': '* Номер тура',
                'verbose_name_plural': '* Номера туров',
            },
        ),
        migrations.CreateModel(
            name='TourNumberType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название номера')),
                ('descr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание номера')),
                ('color_title', models.CharField(blank=True, max_length=10, null=True, verbose_name='Цвет заголовка')),
                ('color_price', models.CharField(blank=True, max_length=10, null=True, verbose_name='Цвет цены')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='number_types', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Тип номеров',
                'verbose_name_plural': 'Типы номеров',
            },
        ),
        migrations.CreateModel(
            name='TourNumbersServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=100, verbose_name='Услуга включенного номера')),
                ('hide', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('tour_number', models.ForeignKey(help_text='Укажите конретный номер тура', on_delete=django.db.models.deletion.CASCADE, related_name='number_services', to='tournumbers.tournumbers', verbose_name='Номера туров')),
            ],
            options={
                'verbose_name': 'Услуга номера',
                'verbose_name_plural': 'Услуги номера',
            },
        ),
        migrations.AddField(
            model_name='tournumbers',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournumbers.tournumbertype'),
        ),
        migrations.CreateModel(
            name='NumberCabinets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметьте, если удалён тур', verbose_name='Удалён?')),
                ('number', models.IntegerField(help_text='Номер кабинета пакета, присвоится автоматически, при создании пакета', verbose_name='Порядковый номер')),
                ('humanize_name', models.CharField(blank=True, default=None, help_text='Наименование номера кабинета вручную', max_length=30, null=True, verbose_name='Название кабинета')),
                ('tour_number', models.ForeignKey(help_text='Здесь указывается номер тура', on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='tournumbers.tournumbers', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Кабинет номера тура',
                'verbose_name_plural': 'Кабинеты номера тура',
                'ordering': ('number',),
            },
        ),
    ]
