# Generated by Django 3.2.15 on 2023-02-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournumbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberComfort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название комфорта')),
                ('icon', models.FileField(upload_to='number_icons', verbose_name='Файл иконки')),
            ],
            options={
                'verbose_name': 'Название удобства номера',
                'verbose_name_plural': 'Название удобств номера',
            },
        ),
        migrations.AddField(
            model_name='tournumbers',
            name='comforts',
            field=models.ManyToManyField(blank=True, related_name='numbers', to='tournumbers.NumberComfort', verbose_name='Удобства'),
        ),
    ]
