# Generated by Django 3.2.15 on 2023-02-26 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournumbers', '0003_numbershots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbercabinets',
            name='tour_number',
            field=models.ForeignKey(help_text='Здесь указывается номер тура', on_delete=django.db.models.deletion.CASCADE, related_name='cabinets', to='tournumbers.tournumbers', verbose_name='Номер'),
        ),
    ]
