# Generated by Django 3.2.15 on 2023-03-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournumbers', '0006_auto_20230307_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numbershots',
            old_name='number',
            new_name='tour_number',
        ),
    ]
