# Generated by Django 3.2.15 on 2023-04-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournumbers', '0007_rename_number_numbershots_tour_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournumbers',
            name='capacity',
            field=models.IntegerField(blank=True, default=1, verbose_name='Вместимость'),
        ),
    ]
