# Generated by Django 3.2.15 on 2023-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournumbers', '0008_tournumbers_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournumbers',
            name='remarks',
            field=models.CharField(blank=True, default='Примечание', max_length=250, null=True, verbose_name='Примечание'),
        ),
    ]
