# Generated by Django 3.2.15 on 2023-04-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournumbers', '0009_alter_tournumbers_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournumbers',
            name='remarks',
            field=models.CharField(blank=True, default='Примечание', max_length=1000, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='tournumbers',
            name='title',
            field=models.CharField(default='1 местн. номера', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tournumbersservices',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Услуга включенного номера'),
        ),
    ]
