# Generated by Django 3.2.15 on 2023-05-02 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournumbers', '0011_auto_20230502_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournumbers',
            name='capacity',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='tournumbers',
            name='extra_capacity_price',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Цена за доп. место'),
        ),
        migrations.AlterField(
            model_name='tournumbers',
            name='max_capacity',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Макс. Вместимость'),
        ),
        migrations.AlterField(
            model_name='tournumbers',
            name='place_count',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
