# Generated by Django 3.2.15 on 2023-05-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournumbers', '0012_auto_20230502_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournumbers',
            name='extra_capacity_price',
            field=models.IntegerField(default=0, verbose_name='Цена за доп. место'),
        ),
    ]
