# Generated by Django 3.2.15 on 2023-05-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournumbers', '0013_alter_tournumbers_extra_capacity_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournumbers',
            name='holiday_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена выходного дня'),
        ),
    ]
