# Generated by Django 3.2.15 on 2024-03-14 19:49

import django.contrib.postgres.fields.ranges
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметьте, если удалён тур', verbose_name='Удалён?')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('closed_for_repair', models.BooleanField(default=False, help_text='Отметить истина, если закрыт на ремонт', verbose_name='Закрыт на ремонт')),
                ('reservation_date', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('paid', models.BooleanField(default=False, help_text='Оплачен ли резерв', verbose_name='Оплачено')),
                ('rated', models.BooleanField(default=False, help_text='Оценена ли резервация', verbose_name='Оценено')),
                ('amount', models.IntegerField(verbose_name='Общая сумма брони')),
                ('amountOfAdults', models.IntegerField(blank=True, default=0, null=True)),
                ('amountOfChildren', models.IntegerField(blank=True, default=0, null=True)),
                ('fullName', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, default='Примечание', max_length=50, null=True, verbose_name='Примечание')),
                ('approved_status', models.SmallIntegerField(choices=[(-1, 'Сообщение не отправлено'), (0, 'Сообщение отправлено'), (1, 'Подтверждено')], default=-1, verbose_name='Статус подтверждения')),
            ],
            options={
                'verbose_name': 'Бронирование отдельного кабинета тура',
                'verbose_name_plural': '1. Бронь кабинета туров',
                'default_related_name': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='ReservationsPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationsServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_services', to='sanatorium.reservations', verbose_name='Бронь')),
            ],
        ),
    ]
