# Generated by Django 3.2.15 on 2023-02-10 09:05

from django.conf import settings
import django.contrib.postgres.fields.ranges
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourpackages', '0001_initial'),
        ('users', '0002_auto_20230210_1505'),
        ('tournumbers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметьте, если удалён тур', verbose_name='Удалён?')),
                ('closed_for_repair', models.BooleanField(default=False, help_text='Отметить истина, если закрыт на ремонт', verbose_name='Закрыт на ремонт')),
                ('reservation_date', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('paid', models.BooleanField(default=False, help_text='Оплачен ли резерв', verbose_name='Оплачено')),
                ('rated', models.BooleanField(default=False, help_text='Оценена ли резервация', verbose_name='Оценено')),
                ('amount', models.IntegerField(verbose_name='Общая сумма брони')),
                ('amountOfAdults', models.IntegerField(blank=True, default=0, null=True)),
                ('amountOfChildren', models.IntegerField(blank=True, default=0, null=True)),
                ('fullName', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, default='Примечание', max_length=50, null=True, verbose_name='Примечание')),
                ('number', models.ForeignKey(help_text='Указывается кабинет номера', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tournumbers.tournumbers')),
                ('number_cabinets', models.ForeignKey(blank=True, help_text='Выберите комнату для резерва', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='tournumbers.numbercabinets', verbose_name='Номер комнаты')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_reservations', to='users.organization')),
                ('reservator', models.ForeignKey(blank=True, help_text='Резервирующим может быть и юрлицо и физлицо.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Резервирующий аккаунт')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='san_reservations', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Бронирование отдельного кабинета тура',
                'verbose_name_plural': '1. Бронь кабинета туров',
                'default_related_name': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='ReservationsServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_services', to='sanatorium.reservations', verbose_name='Бронь')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_services', to='tours.tourpaidservices')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationsPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_packages', to='tourpackages.tourpackages')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_packages', to='sanatorium.reservations', verbose_name='Бронь')),
            ],
        ),
        migrations.CreateModel(
            name='RatedReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanatorium_rates', to='tours.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanatorium_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка тура',
                'verbose_name_plural': '2. Оценки тура',
                'default_related_name': 'sanatorium_rates',
            },
        ),
    ]
