# Generated by Django 3.2.15 on 2024-03-14 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournumbers', '0002_initial'),
        ('tourpackages', '0002_tourpackages_tour'),
        ('tours', '0001_initial'),
        ('sanatorium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationsservices',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_services', to='tours.tourpaidservices'),
        ),
        migrations.AddField(
            model_name='reservationspackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_packages', to='tourpackages.tourpackages'),
        ),
        migrations.AddField(
            model_name='reservationspackage',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_packages', to='sanatorium.reservations', verbose_name='Бронь'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='number',
            field=models.ForeignKey(help_text='Указывается кабинет номера', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tournumbers.tournumbers'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='number_cabinets',
            field=models.ForeignKey(blank=True, help_text='Выберите комнату для резерва', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='tournumbers.numbercabinets', verbose_name='Номер комнаты'),
        ),
    ]
