# Generated by Django 3.2.15 on 2023-02-26 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournumbers', '0004_alter_numbercabinets_tour_number'),
        ('sanatorium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='number_cabinets',
            field=models.ForeignKey(blank=True, default=1, help_text='Выберите комнату для резерва', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='tournumbers.numbercabinets', verbose_name='Номер комнаты'),
            preserve_default=False,
        ),
    ]
