# Generated by Django 3.2.15 on 2024-03-14 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanatorium', '0002_initial'),
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_reservations', to='users.organization'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='san_reservations', to='orders.payment'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='reservator',
            field=models.ForeignKey(blank=True, help_text='Резервирующим может быть и юрлицо и физлицо.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Резервирующий аккаунт'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='san_reservations', to='tours.tour'),
        ),
    ]
