# Generated by Django 3.2.15 on 2023-03-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0002_alter_reservations_number_cabinets'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
