# Generated by Django 3.2.15 on 2023-04-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0004_alter_reservations_deleted_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatedReservation',
        ),
    ]
