# Generated by Django 3.2.15 on 2023-04-28 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_servicecartvisitors_citizenship'),
        ('sanatorium', '0005_delete_ratedreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='payment_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='orders.payment'),
        ),
    ]
