# Generated by Django 3.2.15 on 2023-05-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_payment_reservation'),
        ('sanatorium', '0007_reservations_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='payment_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='san_reservations', to='orders.payment'),
        ),
    ]
