# Generated by Django 3.2.15 on 2023-05-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0009_auto_20230522_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='approved_status',
            field=models.SmallIntegerField(choices=[(-1, 'Сообщение не отправлено'), (0, 'Сообщение отправлено'), (1, 'Подтверждено')], default=-1, verbose_name='Статус подтверждения'),
        ),
    ]
