# Generated by Django 3.2.15 on 2024-03-14 19:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import medtour.orders.instances


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма оплаты')),
                ('status', models.IntegerField(choices=[(0, 'Не оплачено'), (1, 'Оплачено')], default=0, verbose_name='Статус оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_partial', models.BooleanField(default=False, verbose_name='Частичная оплата')),
                ('amount_paid_part', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент частичной оплаты')),
                ('redirect_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='Страница с оплатой платежной системы')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=medtour.orders.instances.get_pdf_path)),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.CreateModel(
            name='ServiceCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(help_text='Дата начала тура', verbose_name='Дата начала тура')),
                ('end', models.DateField(help_text='Дата окончания тура', verbose_name='Дата окончания тура')),
                ('count', models.IntegerField(default=1, help_text='Количество человек', verbose_name='Количество человек')),
                ('price', models.IntegerField(default=0, help_text='Общая цена при покупке тура', verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Корзина тура',
                'verbose_name_plural': 'Корзина туров',
            },
        ),
        migrations.CreateModel(
            name='ServiceCartPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Пакет корзины тура',
                'verbose_name_plural': 'Пакеты корзины тура',
            },
        ),
        migrations.CreateModel(
            name='ServiceCartServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Услуга корзины тура',
                'verbose_name_plural': 'Услуги корзины тура',
            },
        ),
        migrations.CreateModel(
            name='ServiceCartVisitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birthday_date', models.DateField(verbose_name='Дата рождения')),
                ('citizenship', models.CharField(max_length=50, verbose_name='Код страны')),
                ('document', models.IntegerField(choices=[(0, 'Удостоверение личности'), (1, 'Паспорт'), (2, 'Свидетельство о рождении')], verbose_name='Тип документа')),
                ('doc_number', models.CharField(max_length=20, verbose_name='Номер документа')),
                ('gender', models.IntegerField(choices=[(0, 'Мужчина'), (1, 'Женщина')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Пол')),
                ('service_cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='orders.servicecart', verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Посетитель тура',
                'verbose_name_plural': 'Посетители тура',
            },
        ),
    ]
