# Generated by Django 3.2.15 on 2023-02-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kassa24Credentials',
        ),
    ]
