# Generated by Django 3.2.15 on 2023-02-17 16:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_kassa24credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCartVisitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birthday_date', models.DateField(verbose_name='Дата рождения')),
                ('citizenship', models.CharField(max_length=5, verbose_name='Код страны')),
                ('document', models.IntegerField(choices=[(0, 'Удостоверение личности'), (1, 'Паспорт'), (2, 'Свидетельство о рождении')], verbose_name='Тип документа')),
                ('doc_number', models.CharField(max_length=20, verbose_name='Номер документа')),
                ('gender', models.IntegerField(choices=[(0, 'Мужчина'), (1, 'Женщина')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Пол')),
                ('service_cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='orders.servicecart', verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Посетитель тура',
                'verbose_name_plural': 'Посетители тура',
            },
        ),
    ]
