# Generated by Django 3.2.15 on 2023-02-23 22:25

from django.db import migrations, models
import medtour.orders.instances


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_servicecartvisitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=medtour.orders.instances.get_pdf_path),
        ),
    ]
