# Generated by Django 3.2.15 on 2023-03-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_payment_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecartvisitors',
            name='citizenship',
            field=models.CharField(max_length=50, verbose_name='Код страны'),
        ),
    ]
