# Generated by Django 3.2.15 on 2023-04-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_servicecartvisitors_citizenship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reservation',
        ),
    ]
