# Generated by Django 4.1.9 on 2023-06-30 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0022_alter_tourbookingweekdays_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("guides", "0024_program_programservices_and_more"),
        ("orders", "0007_remove_payment_reservation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("check_id", models.CharField(max_length=25, verbose_name="check_id")),
                ("email", models.CharField(blank=True, max_length=100, null=True, verbose_name="email")),
                ("phone", models.CharField(blank=True, max_length=20, null=True, verbose_name="phone")),
                ("total", models.CharField(blank=True, max_length=50, null=True, verbose_name="total")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
            ],
        ),
        migrations.CreateModel(
            name="GuideOrders",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count", models.IntegerField(verbose_name="Количество")),
                ("price", models.IntegerField(verbose_name="Цена")),
                ("sum_total", models.IntegerField(verbose_name="Итоговая сумма")),
                (
                    "total",
                    models.IntegerField(
                        default=models.IntegerField(verbose_name="Итоговая сумма"),
                        verbose_name="Общая сумма с применением скидки",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="guides.program")),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tours.tour")),
                (
                    "transaction",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orders.transactions"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
