# Generated by Django 3.2.15 on 2023-02-10 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20230210_1505'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('phoneNumber', models.CharField(max_length=16, verbose_name='Телефонный номер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.organizationcategory', verbose_name='Тип тура')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Заявка тура',
                'verbose_name_plural': 'Заявки туров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gayrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TourApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
            options={
                'verbose_name': 'Заявка индивидуального тура',
                'verbose_name_plural': 'Заявки индивидуального туров',
            },
        ),
        migrations.CreateModel(
            name='CommentTourApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_comments', to='applications.tourapplication')),
            ],
            options={
                'verbose_name': 'Примечание индивидуальной заявки к туру',
                'verbose_name_plural': 'Примечания индивидуальной заявки к турам',
            },
        ),
    ]
