# Generated by Django 3.2.15 on 2023-05-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gayrat',
        ),
    ]
