# Generated by Django 3.2.15 on 2024-03-14 19:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import medtour.tours.instances
import multiselectfield.db.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfoServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=1000, verbose_name='Наименование услуги')),
            ],
            options={
                'verbose_name': 'Бесплатная услуга',
                'verbose_name_plural': 'Бесплатные услуги тура',
            },
        ),
        migrations.CreateModel(
            name='AdditionalTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Готовая заголовка доп. услуги',
                'verbose_name_plural': 'Готовые заголовки доп. услуг',
            },
        ),
        migrations.CreateModel(
            name='CommentTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Чистота')),
                ('service', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Сервис')),
                ('location', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Местоположение')),
                ('staff', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Персонал')),
                ('proportion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Соотношение цена/качество')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(20, message='Минимальная длина отзыва должна превышать 20 символа')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв тура',
                'verbose_name_plural': 'Отзывы тура',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметьте, если удалён тур', verbose_name='Удалён?')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=1000, verbose_name='Название тура')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('currency', models.IntegerField(blank=True, choices=[(0, 'USD'), (1, 'KZT'), (2, 'UZS'), (3, 'KGS'), (4, 'EUR')], default=1, null=True, verbose_name='Валюта')),
                ('BIN', models.CharField(blank=True, max_length=16, null=True)),
                ('IIK', models.CharField(blank=True, max_length=50, null=True)),
                ('BIK', models.CharField(blank=True, max_length=15, null=True)),
                ('requisites', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Для предоплаты (IBAN)')),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Слаг')),
                ('email', models.EmailField(blank=True, help_text='Пожалуйста напишите ваш эмейл', max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя директора')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия директора')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='Район')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('home_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер дома')),
                ('youtube_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на Youtube')),
                ('working_time', models.TextField(blank=True, null=True, verbose_name='Время работы')),
                ('is_top', models.BooleanField(default=False, verbose_name='Хиты продаж?')),
                ('is_moderated', models.BooleanField(db_index=True, default=False, verbose_name='Прошел модерацию')),
                ('is_subscribed', models.BooleanField(db_index=True, default=False, help_text='Отметьте, если он подписан', verbose_name='Подписан?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '* Тур',
                'verbose_name_plural': '* Туры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourMedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Медицинский профиль',
                'verbose_name_plural': 'Медицинские профили',
            },
        ),
        migrations.CreateModel(
            name='TourShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Имя изображения')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to=medtour.tours.instances.get_shots_path, verbose_name='Изображение')),
                ('tour', models.ForeignKey(help_text='Прикрепленный тур', on_delete=django.db.models.deletion.CASCADE, related_name='tour_shots', to='tours.tour', verbose_name='Изображения тура')),
            ],
            options={
                'verbose_name': 'Изображения тура',
                'verbose_name_plural': 'Изображения туров',
            },
        ),
        migrations.CreateModel(
            name='TourPriceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=medtour.tours.instances.get_price_path)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_file', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourPhones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефонный номер')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_phones', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Телефонный номер тура',
                'verbose_name_plural': 'Телефонные номера тура',
            },
        ),
        migrations.CreateModel(
            name='TourPaidServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(help_text='Наименование платной услуги', max_length=1000, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, help_text='Описание конкретной услуги', null=True, verbose_name='Описание услуги')),
                ('price', models.IntegerField(help_text='Стоимость платной услуги', verbose_name='Стоимость услуги')),
                ('hide', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('tour', models.ForeignKey(help_text='Прикрепленный тур', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tours.tour', verbose_name='Прикрепленный тур')),
            ],
            options={
                'verbose_name': '* Платная услуга тура',
                'verbose_name_plural': '* Платные услуги тура',
            },
        ),
        migrations.CreateModel(
            name='TourLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Локация тура',
                'verbose_name_plural': 'Локации тура',
            },
        ),
        migrations.CreateModel(
            name='TourBookingWeekDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'ПОНЕДЕЛЬНИК'), (2, 'ВТОРНИК'), (3, 'СРЕДА'), (4, 'ЧЕТВЕРГ'), (5, 'ПЯТНИЦА'), (6, 'СУББОТА'), (0, 'ВОСКРЕСЕНЬЕ')], default=[1, 2, 3, 4, 5, 6, 0], max_length=13)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
            options={
                'verbose_name': 'День бронирования тура',
                'verbose_name_plural': 'Дни бронирований тура',
            },
        ),
        migrations.CreateModel(
            name='TourBookingHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'ПОНЕДЕЛЬНИК'), (2, 'ВТОРНИК'), (3, 'СРЕДА'), (4, 'ЧЕТВЕРГ'), (5, 'ПЯТНИЦА'), (6, 'СУББОТА'), (0, 'ВОСКРЕСЕНЬЕ')], default=[6, 0], max_length=13)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holiday', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Выходные дни тура',
                'verbose_name_plural': 'Выходные дни тура',
            },
        ),
        migrations.CreateModel(
            name='TourBookingExtraHolidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='День года')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_days', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Выходные дополнительные дни тура',
                'verbose_name_plural': 'Выходные дополнительные дни тура',
            },
        ),
        migrations.CreateModel(
            name='TourAdditionalTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_titles', to='tours.additionaltitles')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_titles', to='tours.tour')),
            ],
            options={
                'verbose_name': '* Заголовка бесплатных услуг',
                'verbose_name_plural': '* Заголовки бесплатных услуг',
            },
        ),
    ]
