# Generated by Django 3.2.15 on 2023-02-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(default='Title', max_length=100, verbose_name='Название тура'),
            preserve_default=False,
        ),
    ]
