# Generated by Django 3.2.15 on 2023-02-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='publicId',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='short_desc',
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
