# Generated by Django 3.2.15 on 2023-02-18 15:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20230213_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='working_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tourbookingweekdays',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'ВОСКРЕСЕНЬЕ'), (1, 'ПОНЕДЕЛЬНИК'), (2, 'ВТОРНИК'), (3, 'СРЕДА'), (4, 'ЧЕТВЕРГ'), (5, 'ПЯТНИЦА'), (6, 'СУББОТА')], default=[0, 1, 2, 3, 4, 5, 6], max_length=13),
        ),
    ]
