# Generated by Django 3.2.15 on 2023-03-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20230218_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_subscribed',
            field=models.BooleanField(db_index=True, default=False, help_text='Отметьте, если он подписан', verbose_name='Подписан?'),
        ),
    ]
