# Generated by Django 3.2.15 on 2023-03-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tour_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
