# Generated by Django 3.2.15 on 2023-03-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_auto_20230306_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
