# Generated by Django 3.2.15 on 2023-03-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_tour_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Отметьте, если удалён тур', verbose_name='Удалён?'),
        ),
    ]
