# Generated by Django 3.2.15 on 2023-03-21 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_tour_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttour',
            name='staff',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Персонал'),
        ),
    ]
