# Generated by Django 3.2.15 on 2023-05-24 13:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_auto_20230413_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbookingweekdays',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'ПОНЕДЕЛЬНИК'), (2, 'ВТОРНИК'), (3, 'СРЕДА'), (4, 'ЧЕТВЕРГ'), (5, 'ПЯТНИЦА'), (6, 'СУББОТА'), (7, 'ВОСКРЕСЕНЬЕ')], default=[1, 2, 3, 4, 5, 6, 7], max_length=13),
        ),
    ]
