# Generated by Django 3.2.15 on 2023-05-24 16:55

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


def create_objects(apps, schema_editor):
    TourModel = apps.get_model('tours', 'Tour')
    Model = apps.get_model('tours', 'TourBookingHoliday')
    # Replace <app_name> with the name of your Django app
    # Replace <model_name> with the name of the model you want to create objects for
    for tour in TourModel.objects.all():
        # Create objects
        Model.objects.create(tour=tour)
        # Repeat the above line for each object you want to create


def reverse_create_objects(apps, schema_editor):
    # Object removal code
    ...


class Migration(migrations.Migration):
    dependencies = [
        ('tours', '0015_alter_tourbookingweekdays_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBookingHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', multiselectfield.db.fields.MultiSelectField(
                    choices=[(1, 'ПОНЕДЕЛЬНИК'), (2, 'ВТОРНИК'), (3, 'СРЕДА'), (4, 'ЧЕТВЕРГ'), (5, 'ПЯТНИЦА'),
                             (6, 'СУББОТА'), (7, 'ВОСКРЕСЕНЬЕ')], default=[6, 7], max_length=13)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holiday',
                                              to='tours.tour')),
            ],
            options={
                'verbose_name': 'Выходные дни тура',
                'verbose_name_plural': 'Выходные дни тура',
            },
        ),
        migrations.CreateModel(
            name='TourBookingExtraHolidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='День года')),
                ('tour_holidays',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_days',
                                   to='tours.tourbookingholiday')),
            ],
            options={
                'verbose_name': 'Выходные дополнительные дни тура',
                'verbose_name_plural': 'Выходные дополнительные дни тура',
            },
        ),
        migrations.RunPython(create_objects, reverse_create_objects),
    ]
