# Generated by Django 3.2.15 on 2023-05-25 07:26

from django.db import migrations
import multiselectfield.db.fields

def create_objects(apps, schema_editor):
    TourModel = apps.get_model('tours', 'Tour')
    Model = apps.get_model('tours', 'TourBookingHoliday')
    Model2 = apps.get_model('tours', 'TourBookingWeekDays')
    # Replace <app_name> with the name of your Django app
    # Replace <model_name> with the name of the model you want to create objects for
    for tour in TourModel.objects.all():
        # Create objects
        if hasattr(tour, "tourbookingweekdays") is False:
            Model2.objects.create(tour=tour)
        if hasattr(tour, "holiday") is False:
            Model.objects.create(tour=tour)
        # Repeat the above line for each object you want to create


def reverse_create_objects(apps, schema_editor):
    # Object removal code
    ...


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_tourbookingextraholidays_tourbookingholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbookingholiday',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'ПОНЕДЕЛЬНИК'), (2, 'ВТОРНИК'), (3, 'СРЕДА'), (4, 'ЧЕТВЕРГ'), (5, 'ПЯТНИЦА'), (6, 'СУББОТА'), (0, 'ВОСКРЕСЕНЬЕ')], default=[6, 0], max_length=13),
        ),
        migrations.AlterField(
            model_name='tourbookingweekdays',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'ПОНЕДЕЛЬНИК'), (2, 'ВТОРНИК'), (3, 'СРЕДА'), (4, 'ЧЕТВЕРГ'), (5, 'ПЯТНИЦА'), (6, 'СУББОТА'), (0, 'ВОСКРЕСЕНЬЕ')], default=[1, 2, 3, 4, 5, 6, 0], max_length=13),
        ),
        migrations.RunPython(create_objects, reverse_create_objects),
    ]
