# Generated by Django 3.2.15 on 2023-05-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_auto_20230525_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourbookingextraholidays',
            name='tour_holidays',
        ),
        migrations.AddField(
            model_name='tourbookingextraholidays',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extra_days', to='tours.tour'),
            preserve_default=False,
        ),
    ]
