# Generated by Django 3.2.15 on 2023-06-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_auto_20230525_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalInfoTitle',
            new_name='TourAdditionalTitle',
        ),
        migrations.RenameModel(
            old_name='TourPrice',
            new_name='TourPriceFile',
        ),
        migrations.AlterModelOptions(
            name='additionaltitles',
            options={'verbose_name': 'Готовая заголовка доп. услуги', 'verbose_name_plural': 'Готовые заголовки доп. услуг'},
        ),
    ]
