# Generated by Django 3.2.15 on 2023-06-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_city'),
        ('tours', '0019_auto_20230602_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_cities', to='users.city', verbose_name='Город'),
        ),
    ]
