# Generated by Django 4.1.9 on 2023-06-13 17:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0021_tour_is_top"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourbookingweekdays",
            name="days",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (1, "ПОНЕДЕЛЬНИК"),
                    (2, "ВТОРНИК"),
                    (3, "СРЕДА"),
                    (4, "ЧЕТВЕРГ"),
                    (5, "ПЯТНИЦА"),
                    (6, "СУББОТА"),
                    (0, "ВОСКРЕСЕНЬЕ"),
                ],
                default=3,
                max_length=13,
            ),
        ),
    ]
