# Generated by Django 3.2.15 on 2024-03-14 19:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название пакета')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('numbers_of_months', models.SmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуален ли?')),
            ],
            options={
                'verbose_name': 'Стоимость подписки',
                'verbose_name_plural': 'Стоимость подписок',
            },
        ),
        migrations.CreateModel(
            name='SubscribeQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TourSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('overdue', models.BooleanField(default=False)),
                ('payment_receipt', models.CharField(blank=True, max_length=255, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('subscribe_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscribeprice', verbose_name='Тип подписки')),
            ],
            options={
                'verbose_name': 'Подписка тура',
                'verbose_name_plural': 'Подписки туров',
            },
        ),
    ]
