# Generated by Django 3.2.15 on 2023-02-10 09:05

from django.db import migrations, models
import django.db.models.deletion
import medtour.users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ('-created_at',), 'verbose_name': '4. Код подтверждения', 'verbose_name_plural': '4. Коды подтверждения'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('is_moderated',), 'verbose_name': '3. Организация', 'verbose_name_plural': '3. Организации'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', medtour.users.managers.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='category',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='country',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='district',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='home_number',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='region',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='street',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='organizationcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_countries', to='users.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='person',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='person',
            name='home_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='person',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_regions', to='users.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='person',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='bin',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, verbose_name='БИН организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='users.user', verbose_name='Основной аккаунт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default=1, max_length=150, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='iin',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='ИИН пользователя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default=1, max_length=150, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
