# Generated by Django 3.2.15 on 2023-03-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230307_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('sanatorium', 'Санаторий'), ('zonaotdyxa', 'Зона отдыха'), ('guide', 'Гиды')], default='sanatorium', max_length=15, verbose_name='Тип организации'),
        ),
    ]
