# Generated by Django 3.2.15 on 2023-04-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pick',
            field=models.CharField(choices=[('resort', 'Resort'), ('guide', 'Guide'), ('client', 'Client')], default='client', max_length=20, verbose_name='Выбор типа'),
        ),
    ]
