# Generated by Django 3.2.15 on 2023-06-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230608_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationcategory',
            old_name='icons',
            new_name='icon',
        ),
        migrations.AddField(
            model_name='organizationcategory',
            name='column',
            field=models.CharField(default='two', max_length=10),
        ),
        migrations.AddField(
            model_name='organizationcategory',
            name='icon_active',
            field=models.ImageField(default='/static/images/cart.svg', upload_to='category_icons'),
        ),
        migrations.AddField(
            model_name='organizationcategory',
            name='title_color',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
    ]
