# Generated by Django 3.2.15 on 2023-02-10 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        ('tournumbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('is_deleted', models.BooleanField(default=False, help_text='Отметьте, если удалён тур', verbose_name='Удалён?')),
                ('title', models.CharField(help_text='Примерное наименование: Комфорт, Стандарт, Номер на 1 человек', max_length=100, verbose_name='Название пакета')),
                ('price', models.IntegerField()),
                ('hide', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('remarks', models.CharField(blank=True, default='Примечание', max_length=50, null=True, verbose_name='Примечание')),
                ('number', models.ForeignKey(help_text='Укажите сколько местный кабинет в туре', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='tournumbers.tournumbers', verbose_name='Номер пакета')),
                ('tour', models.ForeignKey(help_text='Указывайте для прикрепления к туру', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': '* Тур пакет',
                'verbose_name_plural': '* Тур пакеты',
            },
        ),
        migrations.CreateModel(
            name='TourPackagesServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Услуга сервиса')),
                ('hide', models.BooleanField(default=False, verbose_name='Скрыть')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_services', to='tourpackages.tourpackages')),
            ],
            options={
                'verbose_name': 'Услуга пакета',
                'verbose_name_plural': 'Услуги пакета',
            },
        ),
    ]
