# Generated by Django 3.2.15 on 2023-03-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackages',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
