# Generated by Django 3.2.15 on 2023-03-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0002_tourpackages_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackages',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
