# Generated by Django 3.2.15 on 2023-05-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0004_auto_20230413_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackages',
            name='holiday_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена выходного дня'),
        ),
        migrations.AlterField(
            model_name='tourpackages',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
