# Generated by Django 3.2.15 on 2024-03-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kassa24Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('is_test', models.BooleanField(default=True, verbose_name='Это тест?')),
            ],
            options={
                'verbose_name': 'Платежные данные касса24',
                'verbose_name_plural': 'Платежные данные касса24',
            },
        ),
    ]
