# Generated by Django 3.2.15 on 2023-02-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kassa24Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('is_test', models.BooleanField(default=True, verbose_name='Это тест?')),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kassa24', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Платежные данные касса24',
                'verbose_name_plural': 'Платежные данные касса24',
            },
        ),
    ]
