# Generated by Django 3.2.15 on 2024-03-14 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paycredentials', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kassa24credentials',
            name='tour',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kassa24', to='tours.tour'),
        ),
    ]
